### ISSUE TITLE
Bibliography not IUBH standard

### ISSUE THREAD

**Issue by client-side96** [IUBH-IT-Technik-Profs-Sandbox/LaTeX-IUBH-Template#2]
Hello altogether,
is there a possibility to adapt the citation style to the IUBH standard? I kind of wondered if someone already adapted a `.bst` file to use it with any kind of thesis of the IUBH.

**Comment by polx** [comment]
Hello @client-side96,
well this was discussed but there are field specific practices that keep byting and the IU format is said to be APA but is not completely APA. APA is known to be a monster and I recommend no-one to try implementing such a bst. 
We're opened to pull requests though!
paul

**Comment by client-side96** [comment]
HI @polx . Yeah I noted that the APA bst is quite complex. There is though a bst generator that guides you step by step through the creation process and gives you a starting point for customising it to the IU format. For my last project report I did this, but faced some issues regarding the capitalisation of the source title names and spaces between the words.
I will try to go further and fix them and create a PR. 
For reference I will attach the bst and a screenshot of the current state. If someone has any recommendations I would appreciate them.  

<img width="1278" alt="screenshot-bib" src="https://user-images.githubusercontent.com/34790329/121679800-09605200-cab9-11eb-9043-c73694f3794e.png">

[iubh-example.bst.zip](https://github.com/IUBH-IT-Technik-Profs-Sandbox/LaTeX-IUBH-Template/files/6637990/iubh-example.bst.zip)

**Comment by polx** [comment]
I think apacite might be a good start?
Your example is quite helpful already.
I'd incorporate this as an alternative until we're sure it can work for everyone.

**Comment by client-side96** [comment]
I created a PR and fixed all the issues I had previously with the bst settings. I used the IU thesis book as the reference of the citation style and created some examples for a book citation, collection and article.

**Comment by polx** [comment]
Thanks. All done.
